site_name: Card Interface
site_url: https://djplaner.github.io/Card-Interface-Tweak/
site_author: David Jones
site_description: >-
  Convert a Blackboard Learn content area into a contemporary card interface.

# Configuration
theme:
  name: material

  language: en
#  features:
#    - tabs

nav:
  - Home: 'index.md'
  - Why & What: 'whatWhy.md'
  - Create Cards: 'createCards.md' 
  - Customise a card: 'customiseACard.md'
  - Customise all cards: 'customiseAllCards.md'
markdown_extensions:
  - toc:
      permalink: '#'
      baselevel: 1
